name: Deploy Workflow

on:
  push:
    branches: [ main, master ]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Python project
        run: |
          echo "Building Python project" 

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Hadolint
        run: |
          # Download Hadolint binary
          curl -sSL https://github.com/hadolint/hadolint/releases/download/v2.9.0/hadolint-linux-amd64 -o /usr/local/bin/hadolint
          # Verify download
          ls -l /usr/local/bin/hadolint
          file /usr/local/bin/hadolint
          # Set executable permissions
          chmod +x /usr/local/bin/hadolint
          # Verify it's executable
          hadolint --version

      - name: Lint Dockerfile
        run: hadolint Dockerfile

  deploy-app:
    runs-on: ubuntu-latest
    needs: [build-python, lint-dockerfile]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deploying Python application..."
