
name: Deploy Cloud run

# This workflow is triggered by the completion of the Test, Build, and scan workflows only on main branch.
on:
    workflow_run:
      workflows: [Test, Build, scan]
      types:
        - completed
      
env: 
  DOCKER_IMAGE: docker.io/ocebr/isen-python:1.0.0-dev-${{ github.sha }}
  REGION: europe-west1

jobs:
  deploy_cloud_run:
    runs-on: ubuntu-24.04
    steps:
    - uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
    - run:  |
        # Like Docker login but for Artifact Registry of Google Cloud
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
        # Pulling previously built image from Docker Hub, to tag it and push it to Google Artifact Registry
        docker pull $DOCKER_IMAGE
        docker tag $DOCKER_IMAGE ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/isen-python-app/isen-python:1.0.0-dev-${{ github.sha }}
        docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/isen-python-app/isen-python:1.0.0-dev-${{ github.sha }}
    - id: 'deploy'
    # Using the Google Cloud Run action to deploy the image to Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: 'isen-python-app'
        image: ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT_ID }}/isen-python-app/isen-python:1.0.0-dev-${{ github.sha }}

