name: Deploy Workflow

on:
  push:
    branches: [ main, master ]
  
jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Install Pylint
        run: pip install pylint  # Install Pylint

      - name: Run Pylint
        run: pylint **/*.py  # Lint all Python files in the repository
        
      - name: Build Python project (if needed)
        run: |
          echo "Building Python project"  # Add any build steps for Python here if needed

  deploy-app:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: echo "Deploying Python application..."
