name: Pylint

on: [push]

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Run Pylint
        run: |
          pylint --disable=C,R0801 --fail-under=7 $(git ls-files '*.py')