name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyse with pylint
        run: |
          # disable unwanted checks (C codes and duplicate-code R0801)
          # and require at least a 7.0 score to pass
          pylint --disable=C,R0801 --fail-under=7 $(git ls-files '*.py')
