name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pylint

      - name: Analyse with pylint
        run: |
          # disable convention(C), duplicate-code(R0801)
          # require at least 7.0 to pass
          pylint --disable=C,R0801 --fail-under=7 $(git ls-files '*.py')
