generate-sbom:
  name: Generate SBOM
  runs-on: ubuntu-latest
  needs: build-and-push

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate SBOM
      uses: anchore/sbom-action@v0.15.0
      with:
        path: "."
        output-file: "sbom.syft.json"
        format: "syft-json"

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: sbom.syft.json
