scan-sbom:
  name: Scan SBOM
  runs-on: ubuntu-latest
  needs: generate-sbom

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download SBOM
      uses: actions/download-artifact@v4
      with:
        name: sbom

    - name: Scan SBOM
      uses: anchore/scan-action@v3
      with:
        input: sbom.syft.json
